<a href="https://colab.research.google.com/github/studimeyt/speechRecognition/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow as tf

In [3]:
csv_file = str("/content/drive/MyDrive/MinorProject/voice.csv/voice.csv")
data = pd.read_csv(csv_file)

In [4]:
data

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,male
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,male
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,male
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,male
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,0.131884,0.084734,0.153707,0.049285,0.201144,0.151859,1.762129,6.630383,0.962934,0.763182,...,0.131884,0.182790,0.083770,0.262295,0.832899,0.007812,4.210938,4.203125,0.161929,female
3164,0.116221,0.089221,0.076758,0.042718,0.204911,0.162193,0.693730,2.503954,0.960716,0.709570,...,0.116221,0.188980,0.034409,0.275862,0.909856,0.039062,3.679688,3.640625,0.277897,female
3165,0.142056,0.095798,0.183731,0.033424,0.224360,0.190936,1.876502,6.604509,0.946854,0.654196,...,0.142056,0.209918,0.039506,0.275862,0.494271,0.007812,2.937500,2.929688,0.194759,female
3166,0.143659,0.090628,0.184976,0.043508,0.219943,0.176435,1.591065,5.388298,0.950436,0.675470,...,0.143659,0.172375,0.034483,0.250000,0.791360,0.007812,3.593750,3.585938,0.311002,female
3167,0.165509,0.092884,0.183044,0.070072,0.250827,0.180756,1.705029,5.769115,0.938829,0.601529,...,0.165509,0.185607,0.062257,0.271186,0.227022,0.007812,0.554688,0.546875,0.350000,female

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   object
dtypes: float64(20), object(1)
memory usage: 519.9+ KB

In [6]:
label_encoder = LabelEncoder()

data['label'] = label_encoder.fit_transform(data['label'])

In [7]:
dict(enumerate(label_encoder.classes_))

{0: 'female', 1: 'male'}

In [8]:
data

,meanfreq,sd,median,Q25,Q75,IQR,skew,kurt,sp.ent,sfm,...,centroid,meanfun,minfun,maxfun,meandom,mindom,maxdom,dfrange,modindx,label
0,0.059781,0.064241,0.032027,0.015071,0.090193,0.075122,12.863462,274.402906,0.893369,0.491918,...,0.059781,0.084279,0.015702,0.275862,0.007812,0.007812,0.007812,0.000000,0.000000,1
1,0.066009,0.067310,0.040229,0.019414,0.092666,0.073252,22.423285,634.613855,0.892193,0.513724,...,0.066009,0.107937,0.015826,0.250000,0.009014,0.007812,0.054688,0.046875,0.052632,1
2,0.077316,0.083829,0.036718,0.008701,0.131908,0.123207,30.757155,1024.927705,0.846389,0.478905,...,0.077316,0.098706,0.015656,0.271186,0.007990,0.007812,0.015625,0.007812,0.046512,1
3,0.151228,0.072111,0.158011,0.096582,0.207955,0.111374,1.232831,4.177296,0.963322,0.727232,...,0.151228,0.088965,0.017798,0.250000,0.201497,0.007812,0.562500,0.554688,0.247119,1
4,0.135120,0.079146,0.124656,0.078720,0.206045,0.127325,1.101174,4.333713,0.971955,0.783568,...,0.135120,0.106398,0.016931,0.266667,0.712812,0.007812,5.484375,5.476562,0.208274,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,0.131884,0.084734,0.153707,0.049285,0.201144,0.151859,1.762129,6.630383,0.962934,0.763182,...,0.131884,0.182790,0.083770,0.262295,0.832899,0.007812,4.210938,4.203125,0.161929,0
3164,0.116221,0.089221,0.076758,0.042718,0.204911,0.162193,0.693730,2.503954,0.960716,0.709570,...,0.116221,0.188980,0.034409,0.275862,0.909856,0.039062,3.679688,3.640625,0.277897,0
3165,0.142056,0.095798,0.183731,0.033424,0.224360,0.190936,1.876502,6.604509,0.946854,0.654196,...,0.142056,0.209918,0.039506,0.275862,0.494271,0.007812,2.937500,2.929688,0.194759,0
3166,0.143659,0.090628,0.184976,0.043508,0.219943,0.176435,1.591065,5.388298,0.950436,0.675470,...,0.143659,0.172375,0.034483,0.250000,0.791360,0.007812,3.593750,3.585938,0.311002,0
3167,0.165509,0.092884,0.183044,0.070072,0.250827,0.180756,1.705029,5.769115,0.938829,0.601529,...,0.165509,0.185607,0.062257,0.271186,0.227022,0.007812,0.554688,0.546875,0.350000,0

In [9]:
y = data['label'].copy()
X = data.drop('label', axis=1).copy()

In [10]:
scaler = StandardScaler()

X = scaler.fit_transform(X)

In [11]:
X.shape

(3168, 20)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, random_state=42)

In [13]:
inputs = tf.keras.Input(shape=X.shape[1])

In [14]:
x = tf.keras.layers.Dense(64, activation='relu')(inputs)

outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(inputs, outputs)

In [15]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 20)]              0

 dense (Dense)               (None, 64)                1344

 dense_1 (Dense)             (None, 1)                 65

=================================================================
Total params: 1,409
Trainable params: 1,409
Non-trainable params: 0
_________________________________________________________________

In [16]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[
        'accuracy',
        tf.keras.metrics.AUC(name='auc')
    ]
)

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    batch_size=32,
    epochs=100,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=3,
            restore_best_weights=True
        )
    ]
)

Epoch 1/100
56/56 [==============================] - 2s 9ms/step - loss: 0.5466 - accuracy: 0.7202 - auc: 0.8153 - val_loss: 0.3897 - val_accuracy: 0.9032 - val_auc: 0.9601
Epoch 2/100
56/56 [==============================] - 0s 3ms/step - loss: 0.3306 - accuracy: 0.9064 - auc: 0.9694 - val_loss: 0.2503 - val_accuracy: 0.9527 - val_auc: 0.9905
Epoch 3/100
56/56 [==============================] - 0s 3ms/step - loss: 0.2260 - accuracy: 0.9459 - auc: 0.9879 - val_loss: 0.1754 - val_accuracy: 0.9707 - val_auc: 0.9935
Epoch 4/100
56/56 [==============================] - 0s 3ms/step - loss: 0.1668 - accuracy: 0.9645 - auc: 0.9915 - val_loss: 0.1326 - val_accuracy: 0.9775 - val_auc: 0.9945
Epoch 5/100
56/56 [==============================] - 0s 2ms/step - loss: 0.1331 - accuracy: 0.9650 - auc: 0.9934 - val_loss: 0.1070 - val_accuracy: 0.9797 - val_auc: 0.9959
Epoch 6/100
56/56 [==============================] - 0s 3ms/step - loss: 0.1125 - accuracy: 0.9695 - auc: 0.9944 - val_loss: 0.0919 - val_accuracy: 0.9797 - val_auc: 0.9962
Epoch 7/100
56/56 [==============================] - 0s 3ms/step - loss: 0.1003 - accuracy: 0.9712 - auc: 0.9952 - val_loss: 0.0808 - val_accuracy: 0.9820 - val_auc: 0.9968
Epoch 8/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0901 - accuracy: 0.9718 - auc: 0.9958 - val_loss: 0.0737 - val_accuracy: 0.9820 - val_auc: 0.9970
Epoch 9/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0838 - accuracy: 0.9741 - auc: 0.9960 - val_loss: 0.0704 - val_accuracy: 0.9842 - val_auc: 0.9970
Epoch 10/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0788 - accuracy: 0.9752 - auc: 0.9961 - val_loss: 0.0646 - val_accuracy: 0.9820 - val_auc: 0.9973
Epoch 11/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0750 - accuracy: 0.9757 - auc: 0.9965 - val_loss: 0.0665 - val_accuracy: 0.9820 - val_auc: 0.9968
Epoch 12/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0717 - accuracy: 0.9757 - auc: 0.9967 - val_loss: 0.0586 - val_accuracy: 0.9842 - val_auc: 0.9977
Epoch 13/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0704 - accuracy: 0.9769 - auc: 0.9965 - val_loss: 0.0576 - val_accuracy: 0.9865 - val_auc: 0.9975
Epoch 14/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0685 - accuracy: 0.9769 - auc: 0.9966 - val_loss: 0.0587 - val_accuracy: 0.9865 - val_auc: 0.9973
Epoch 15/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0652 - accuracy: 0.9786 - auc: 0.9969 - val_loss: 0.0555 - val_accuracy: 0.9865 - val_auc: 0.9976
Epoch 16/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0638 - accuracy: 0.9780 - auc: 0.9961 - val_loss: 0.0573 - val_accuracy: 0.9887 - val_auc: 0.9973
Epoch 17/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0625 - accuracy: 0.9786 - auc: 0.9967 - val_loss: 0.0580 - val_accuracy: 0.9865 - val_auc: 0.9972
Epoch 18/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0605 - accuracy: 0.9803 - auc: 0.9972 - val_loss: 0.0530 - val_accuracy: 0.9910 - val_auc: 0.9977
Epoch 19/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0599 - accuracy: 0.9797 - auc: 0.9972 - val_loss: 0.0550 - val_accuracy: 0.9887 - val_auc: 0.9974
Epoch 20/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0579 - accuracy: 0.9814 - auc: 0.9970 - val_loss: 0.0518 - val_accuracy: 0.9910 - val_auc: 0.9978
Epoch 21/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0577 - accuracy: 0.9791 - auc: 0.9974 - val_loss: 0.0512 - val_accuracy: 0.9887 - val_auc: 0.9978
Epoch 22/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0561 - accuracy: 0.9808 - auc: 0.9975 - val_loss: 0.0518 - val_accuracy: 0.9910 - val_auc: 0.9978
Epoch 23/100
56/56 [==============================] - 0s 2ms/step - loss: 0.0549 - accuracy: 0.9814 - auc: 0.9976 - val_loss: 0.0517 - val_accuracy: 0.9910 - val_auc: 0.9977
Epoch 24/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0541 - accuracy: 0.9814 - auc: 0.9976 - val_loss: 0.0507 - val_accuracy: 0.9910 - val_auc: 0.9979
Epoch 25/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0531 - accuracy: 0.9820 - auc: 0.9977 - val_loss: 0.0523 - val_accuracy: 0.9887 - val_auc: 0.9976
Epoch 26/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0530 - accuracy: 0.9825 - auc: 0.9977 - val_loss: 0.0510 - val_accuracy: 0.9910 - val_auc: 0.9976
Epoch 27/100
56/56 [==============================] - 0s 3ms/step - loss: 0.0517 - accuracy: 0.9820 - auc: 0.9977 - val_loss: 0.0510 - val_accuracy: 0.9887 - val_auc: 0.9977

In [20]:
model.evaluate(X_test, y_test)

30/30 [==============================] - 0s 5ms/step - loss: 0.0676 - accuracy: 0.9790 - auc: 0.9973

[0.06755117326974869, 0.9789695143699646, 0.997251033782959]

In [21]:
y_pre=model.predict(X_test[:20])
new_y_pre = []
for i in y_pre:
  if i>0.5:
    new_y_pre.append(1)
  else:
    new_y_pre.append(0)
new_y_pre

[0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

In [22]:
y_test[:20]

2148    0
1124    1
170     1
3158    0
2229    0
1960    0
411     1
457     1
2881    0
602     1
2339    0
2490    0
2315    0
2985    0
2906    0
2421    0
2260    0
2877    0
2550    0
621     1
Name: label, dtype: int64